import React from 'react'
import { AdminContainer } from '../../containers/admin-page'

export const metadata = {
  title: "Quản lý hệ thống",
  description: "Generated by create next app",
};

const AdminPage = ({params}) => {
  return (
    <AdminContainer task={params.task}/>
  )
}

export default AdminPage