import Header from "@/components/Header";
import "./styles/globals.css";
import Footer from "@/components/Footer";
import Thumb from '@/public/images/banner/banner_02.jpg'

export const metadata = {
  title: {
    default: "Ezmom",
    template: "Ezmom - %s",
  },
  image:{Thumb},
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
