import Header from "@/components/Header";
import "./styles/globals.css";
import Footer from "@/components/Footer";
import Thumb from "@/public/images/banner/banner_02.jpg";

export const metadata = {
  title: {
    default: "Ezmom",
    template: "Ezmom - %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta property="og:image" content={Thumb} />
      </head>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
