"use client"
import { useRouter } from 'next/navigation';
import HomePage from './containers/home-page/home.container'

export const metadata = {
  title: "Trang Chủ",
  description: "Generated by create next app",
};

export default function Home() {
  const router = useRouter();
  return (
    <main>
      <HomePage/>
    </main>
  )
}
