import HomePage from './containers/home-page/home.container'

export const metadata = {
  title: "Ezmom - Trang Chủ",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <HomePage/>
    </main>
  )
}
