import React from "react";
import ProfileContainer from "../containers/profile-page/profile.container";

export const metadata = {
  title: "Hồ sơ người dùng",
  description: "Generated by create next app",
};

const Profile = () => {
  return (
    <div className="w-full">
      <ProfileContainer />
    </div>
  );
};

export default Profile;
